[module]
  noProxy = 'none'
  noVendor = ''
  private = '*.*'
  proxy = 'direct'
  replacements = ''
  vendorClosest = false
  workspace = 'off'
  [module.hugoVersion]
    extended = false
    max = '0.126.0'
    min = '0.131.0'
